### ISSUE TITLE
Event format changes

### ISSUE THREAD

**Issue by Didotto** [ForHost/9GUSLauncher#6]
-add a registration close date or a checkbox(closed event) in the new event modification system;
-modify Subscribers from TextBox(string)  type to ListBox;
-modify Event Mods from TextBox(string)  type to ListBox;

**Comment by NukeDev** [comment]
FIXED: 
-modify Subscribers from TextBox(string) type to ListBox;
-modify Event Mods from TextBox(string) type to ListBox;

**Comment by NukeDev** [comment]
ADDED:
-add a registration close date or a checkbox(closed event) in the new event modification system;
